### PR TITLE
Only add "row sep=crcr" if not externalData

### LINKED ISSUE #548: Pgfplots 1.12 incompatible with matlab2tikz('externalData',true)
When used with externalData=true, matlab2tikz 0.6.0 generates code with the table option "row sep=crcr":
```
\addplot [color=black,solid]
table[row sep=crcr]{\relativepath /test-1.tsv};
```
This is not compatible with Pgfplots 1.12 (see http://ctanhg.scharrer-online.de/hg/pgfplots/rev/54e8d4404680), compilation fails with the message:
```
! Package pgfplots Error: Sorry, the choice 'row sep=crcr' is currently only available for inline tables, not for external files.
```
The solution is to remove [row sep=crcr], which did not make sense for external data files anyway.

Also see: #451

### PR DESCRIPTION
**Pull request by egeerardyn**
This fixes #548.

There is a single occurrance where this patch isn't applied yet, since I'm unsure whether that case allows for external tables.
TODOs have been left at that location.

**The correctness has been tested against the framework in #485 (by cherry-picking on top of this and running the suite in R2014b).**
Only `ACID(83)` produces different output. I have diffed the output against the current HEAD of #485 and the difference is an improvement as you can see below (only the different part is shown):

before:
```latex
[row sep=crcr,]{%
```

after (this PR):
```latex
[row sep=crcr]{%
```

So, I think we are better off like this, but this is something we have to look out for after merging #485.

### CODE REVIEW

File: src/matlab2tikz.m [hunk 1]
```diff
@@ -3082,15 +3084,17 @@ case size(cData,2) % specific y-data is given
...
     else
-        metaPart = sprintf('meta index=%d',size(data,2));
+        metaPart = opts_add(metaPart,'meta index', sprintf('%d', size(data,2)));
         data = [data, cData(:)];
         nColumns = nColumns + 1;
     end
 
     % The actual printing.
-    [m2t, table] = makeTable(m2t, repmat({''},1,nColumns), data);
-    str = sprintf('%s\\%s[%s] plot table[row sep=crcr,%s]{%s};\n', str, env, ...
```
Comment (egeerardyn) [inline src/matlab2tikz.m]: This seems to be the culprit for the difference.

File: src/matlab2tikz.m [hunk 2]
```diff
@@ -3289,9 +3295,10 @@ case size(cData,2) % specific y-data is given
         [xDataPlot, yDataPlot] = deal(xData, yData);
     end
 
-    drawOpts = opts_print(m2t, drawOptions, ',');
-    [m2t, table ] = makeTable(m2t, '', xDataPlot, '', yDataPlot);
-    str = sprintf('\\addplot[%s] plot table[row sep=crcr] {%s};\n', drawOpts, table);
+    [m2t, table, tabOpts] = makeTable(m2t, '', xDataPlot, '', yDataPlot);
+    str = sprintf('\\addplot[%s] plot table[%s] {%s};\n', ...
+                 opts_print(m2t, drawOptions, ','), ...
+                 opts_print(m2t, tabOpts, ','), table);
```
Comment (PeterPablo) [inline src/matlab2tikz.m]: Beatify by unifying `tabOpts` and `drawOptions` to both `<x>Opts` or `<x>Options`. This eases search (and replace) for debugging. Applies to the whole code preferably and not only this sub-function.

File: src/matlab2tikz.m [hunk 3]
```diff
@@ -4500,19 +4507,21 @@ case size(cData,2) % specific y-data is given
     end
 end
 % ==============================================================================
-function [m2t, table] = makeTable(m2t, varargin)
+function [m2t, table, opts] = makeTable(m2t, varargin)
 %   [m2t,table] = makeTable(m2t, 'name1', data1, 'name2', data2, ...)
```
Comment (PeterPablo) [inline src/matlab2tikz.m]: `[m2t, table, opts] =`
Applies to the two lines below as well.

File: src/matlab2tikz.m [hunk 4]
```diff
@@ -4500,19 +4507,21 @@ case size(cData,2) % specific y-data is given
...
 %   [m2t,table] = makeTable(m2t, {'name1','name2',...}, {data1, data2, ...})
 %   [m2t,table] = makeTable(m2t, {'name1','name2',...}, [data1(:), data2(:), ...])
 %
 %  When all the names are empty, no header is printed
```
Comment (PeterPablo) [inline src/matlab2tikz.m]: Additional comment `% Return m2t structure, formatted table and table options.`

File: src/matlab2tikz.m (hunk 2 above)
Comment (egeerardyn) [inline src/matlab2tikz.m]: I completely agree with this comment, but let's do that in a different PR. I have some simplifications in my private repo and some other small changes (e.g. use of `opts_…` everywhere), where that seems a better fit since those changes are going to touch the whole code base.

**Comment by PeterPablo** [comment]
This is an elegant solution to the issue brought up in #548. Code looks fine and testsuite ran on top of #485 with octave and R2014b without new issues.

I updated my pgfplots to 1.12 and ensured that output of `testGraphical()` is compilable. Compilation doesn't cause errors but many plots look very wrong now (e.g. `markerSizes2, ACID(5)`).
Since the md5sums still match I fear those are incompatibilities with the new pgfplots version. :-/
Please see for yourself: https://www.wuala.com/PeterPablo/Upload/m2t/acid_0e15888.pdf/?key=zNl74H2fU0k3

--> :+1: for the code
(I don't know about that TODO and did not look into it.)

File: src/matlab2tikz.m (hunk 2 above)
Comment (PeterPablo) [inline src/matlab2tikz.m]: Certainly :-)

**Comment by egeerardyn** [comment]
@PeterPablo Thanks for checking.

I knew I was forgetting something: I haven't installed pgfplots 1.12 yet (but my MacTex didn't want to update yesterday). I will have a go at compiling both with pgfplots 1.12 and 1.11 for comparison.
The TODO is not entirely documented (at some points, I think @okomarov documented that in the code, I try to tackle those things when I address #391), so that's not perfectly clear communication from my part.

**Comment by PeterPablo** [comment]
So I had a look at `test5-converted.tex` and compiled it manually. Long story short:
`pdflatex` is fine
image

`lualatex` fails (used by our `Makefile`)
image

`test5-converted.tex`
```
% This file was created by matlab2tikz.
%
\documentclass[tikz]{standalone}
\usepackage{pgfplots}
\usepackage{grffile}
\pgfplotsset{compat=newest}
\usetikzlibrary{plotmarks}
\usepgfplotslibrary{patchplots}
\usepackage{amsmath}

\begin{document}
\definecolor{mycolor1}{rgb}{0.00000,1.00000,1.00000}%
\definecolor{mycolor2}{rgb}{1.00000,0.00000,1.00000}%
\definecolor{mycolor3}{rgb}{1.00000,1.00000,0.00000}%
%
\begin{tikzpicture}

\begin{axis}[%
width=6.027778in,
height=4.754167in,
at={(1.011111in,0.641667in)},
scale only axis,
xmin=0,
xmax=11,
xtick={1,2,3,4,5,6,7,8,9,10},
xticklabels={{6},{8},{10},{12},{14},{17},{19},{21},{23},{25}},
xmajorgrids,
ymin=0,
ymax=140,
ymajorgrids,
axis background/.style={fill=white},
axis x line*=bottom,
axis y line*=left
]
\addplot [color=blue,only marks,mark=x,mark options={solid},forget plot]
  table[row sep=crcr]{%
1	10\\
};
\addplot [color=blue,mark size=4.0pt,only marks,mark=x,mark options={solid},forget plot]
  table[row sep=crcr]{%
2	10\\
};
\addplot [color=blue,mark size=5.0pt,only marks,mark=x,mark options={solid},forget plot]
  table[row sep=crcr]{%
3	10\\
};
\addplot [color=blue,mark size=6.0pt,only marks,mark=x,mark options={solid},forget plot]
  table[row sep=crcr]{%
4	10\\
};
\addplot [color=blue,mark size=7.0pt,only marks,mark=x,mark options={solid},forget plot]
  table[row sep=crcr]{%
5	10\\
};
\addplot [color=blue,mark size=8.5pt,only marks,mark=x,mark options={solid},forget plot]
  table[row sep=crcr]{%
6	10\\
};
\addplot [color=blue,mark size=9.5pt,only marks,mark=x,mark options={solid},forget plot]
  table[row sep=crcr]{%
7	10\\
};
\addplot [color=blue,mark size=10.5pt,only marks,mark=x,mark options={solid},forget plot]
  table[row sep=crcr]{%
8	10\\
};
\addplot [color=blue,mark size=11.5pt,only marks,mark=x,mark options={solid},forget plot]
  table[row sep=crcr]{%
9	10\\
};
\addplot [color=blue,mark size=12.5pt,only marks,mark=x,mark options={solid},forget plot]
  table[row sep=crcr]{%
10	10\\
};
\addplot [color=red,only marks,mark=diamond,mark options={solid},forget plot]
  table[row sep=crcr]{%
1	20\\
};
\addplot [color=red,mark size=6.9pt,only marks,mark=diamond,mark options={solid},forget plot]
  table[row sep=crcr]{%
2	20\\
};
\addplot [color=red,mark size=8.6pt,only marks,mark=diamond,mark options={solid},forget plot]
  table[row sep=crcr]{%
3	20\\
};
\addplot [color=red,mark size=10.4pt,only marks,mark=diamond,mark options={solid},forget plot]
  table[row sep=crcr]{%
4	20\\
};
\addplot [color=red,mark size=12.1pt,only marks,mark=diamond,mark options={solid},forget plot]
  table[row sep=crcr]{%
5	20\\
};
\addplot [color=red,mark size=14.7pt,only marks,mark=diamond,mark options={solid},forget plot]
  table[row sep=crcr]{%
6	20\\
};
\addplot [color=red,mark size=16.4pt,only marks,mark=diamond,mark options={solid},forget plot]
  table[row sep=crcr]{%
7	20\\
};
\addplot [color=red,mark size=18.1pt,only marks,mark=diamond,mark options={solid},forget plot]
  table[row sep=crcr]{%
8	20\\
};
\addplot [color=red,mark size=19.8pt,only marks,mark=diamond,mark options={solid},forget plot]
  table[row sep=crcr]{%
9	20\\
};
\addplot [color=red,mark size=21.6pt,only marks,mark=diamond,mark options={solid},forget plot]
  table[row sep=crcr]{%
10	20\\
};
\addplot [color=green,only marks,mark=o,mark options={solid},forget plot]
  table[row sep=crcr]{%
1	30\\
};
\addplot [color=green,mark size=4.0pt,only marks,mark=o,mark options={solid},forget plot]
  table[row sep=crcr]{%
2	30\\
};
\addplot [color=green,mark size=5.0pt,only marks,mark=o,mark options={solid},forget plot]
  table[row sep=crcr]{%
3	30\\
};
\addplot [color=green,mark size=6.0pt,only marks,mark=o,mark options={solid},forget plot]
  table[row sep=crcr]{%
4	30\\
};
\addplot [color=green,mark size=7.0pt,only marks,mark=o,mark options={solid},forget plot]
  table[row sep=crcr]{%
5	30\\
};
\addplot [color=green,mark size=8.5pt,only marks,mark=o,mark options={solid},forget plot]
  table[row sep=crcr]{%
6	30\\
};
\addplot [color=green,mark size=9.5pt,only marks,mark=o,mark options={solid},forget plot]
  table[row sep=crcr]{%
7	30\\
};
\addplot [color=green,mark size=10.5pt,only marks,mark=o,mark options={solid},forget plot]
  table[row sep=crcr]{%
8	30\\
};
\addplot [color=green,mark size=11.5pt,only marks,mark=o,mark options={solid},forget plot]
  table[row sep=crcr]{%
9	30\\
};
\addplot [color=green,mark size=12.5pt,only marks,mark=o,mark options={solid},forget plot]
  table[row sep=crcr]{%
10	30\\
};
\addplot [color=mycolor1,only marks,mark=*,mark options={solid},forget plot]
  table[row sep=crcr]{%
1	40\\
};
\addplot [color=mycolor1,mark size=1.3pt,only marks,mark=*,mark options={solid},forget plot]
  table[row sep=crcr]{%
2	40\\
};
\addplot [color=mycolor1,mark size=1.7pt,only marks,mark=*,mark options={solid},forget plot]
  table[row sep=crcr]{%
3	40\\
};
\addplot [color=mycolor1,mark size=2.0pt,only marks,mark=*,mark options={solid},forget plot]
  table[row sep=crcr]{%
4	40\\
};
\addplot [color=mycolor1,mark size=2.3pt,only marks,mark=*,mark options={solid},forget plot]
  table[row sep=crcr]{%
5	40\\
};
\addplot [color=mycolor1,mark size=2.8pt,only marks,mark=*,mark options={solid},forget plot]
  table[row sep=crcr]{%
6	40\\
};
\addplot [color=mycolor1,mark size=3.2pt,only marks,mark=*,mark options={solid},forget plot]
  table[row sep=crcr]{%
7	40\\
};
\addplot [color=mycolor1,mark size=3.5pt,only marks,mark=*,mark options={solid},forget plot]
  table[row sep=crcr]{%
8	40\\
};
\addplot [color=mycolor1,mark size=3.8pt,only marks,mark=*,mark options={solid},forget plot]
  table[row sep=crcr]{%
9	40\\
};
\addplot [color=mycolor1,mark size=4.2pt,only marks,mark=*,mark options={solid},forget plot]
  table[row sep=crcr]{%
10	40\\
};
\addplot [color=mycolor2,only marks,mark=+,mark options={solid},forget plot]
  table[row sep=crcr]{%
1	50\\
};
\addplot [color=mycolor2,mark size=4.0pt,only marks,mark=+,mark options={solid},forget plot]
  table[row sep=crcr]{%
2	50\\
};
\addplot [color=mycolor2,mark size=5.0pt,only marks,mark=+,mark options={solid},forget plot]
  table[row sep=crcr]{%
3	50\\
};
\addplot [color=mycolor2,mark size=6.0pt,only marks,mark=+,mark options={solid},forget plot]
  table[row sep=crcr]{%
4	50\\
};
\addplot [color=mycolor2,mark size=7.0pt,only marks,mark=+,mark options={solid},forget plot]
  table[row sep=crcr]{%
5	50\\
};
\addplot [color=mycolor2,mark size=8.5pt,only marks,mark=+,mark options={solid},forget plot]
  table[row sep=crcr]{%
6	50\\
};
\addplot [color=mycolor2,mark size=9.5pt,only marks,mark=+,mark options={solid},forget plot]
  table[row sep=crcr]{%
7	50\\
};
\addplot [color=mycolor2,mark size=10.5pt,only marks,mark=+,mark options={solid},forget plot]
  table[row sep=crcr]{%
8	50\\
};
\addplot [color=mycolor2,mark size=11.5pt,only marks,mark=+,mark options={solid},forget plot]
  table[row sep=crcr]{%
9	50\\
};
\addplot [color=mycolor2,mark size=12.5pt,only marks,mark=+,mark options={solid},forget plot]
  table[row sep=crcr]{%
10	50\\
};
\addplot [color=mycolor3,only marks,mark=asterisk,mark options={solid},forget plot]
  table[row sep=crcr]{%
1	60\\
};
\addplot [color=mycolor3,mark size=4.0pt,only marks,mark=asterisk,mark options={solid},forget plot]
  table[row sep=crcr]{%
2	60\\
};
\addplot [color=mycolor3,mark size=5.0pt,only marks,mark=asterisk,mark options={solid},forget plot]
  table[row sep=crcr]{%
3	60\\
};
\addplot [color=mycolor3,mark size=6.0pt,only marks,mark=asterisk,mark options={solid},forget plot]
  table[row sep=crcr]{%
4	60\\
};
\addplot [color=mycolor3,mark size=7.0pt,only marks,mark=asterisk,mark options={solid},forget plot]
  table[row sep=crcr]{%
5	60\\
};
\addplot [color=mycolor3,mark size=8.5pt,only marks,mark=asterisk,mark options={solid},forget plot]
  table[row sep=crcr]{%
6	60\\
};
\addplot [color=mycolor3,mark size=9.5pt,only marks,mark=asterisk,mark options={solid},forget plot]
  table[row sep=crcr]{%
7	60\\
};
\addplot [color=mycolor3,mark size=10.5pt,only marks,mark=asterisk,mark options={solid},forget plot]
  table[row sep=crcr]{%
8	60\\
};
\addplot [color=mycolor3,mark size=11.5pt,only marks,mark=asterisk,mark options={solid},forget plot]
  table[row sep=crcr]{%
9	60\\
};
\addplot [color=mycolor3,mark size=12.5pt,only marks,mark=asterisk,mark options={solid},forget plot]
  table[row sep=crcr]{%
10	60\\
};
\addplot [color=blue,only marks,mark=square,mark options={solid},forget plot]
  table[row sep=crcr]{%
1	70\\
};
\addplot [color=blue,mark size=2.8pt,only marks,mark=square,mark options={solid},forget plot]
  table[row sep=crcr]{%
2	70\\
};
\addplot [color=blue,mark size=3.5pt,only marks,mark=square,mark options={solid},forget plot]
  table[row sep=crcr]{%
3	70\\
};
\addplot [color=blue,mark size=4.2pt,only marks,mark=square,mark options={solid},forget plot]
  table[row sep=crcr]{%
4	70\\
};
\addplot [color=blue,mark size=4.9pt,only marks,mark=square,mark options={solid},forget plot]
  table[row sep=crcr]{%
5	70\\
};
\addplot [color=blue,mark size=6.0pt,only marks,mark=square,mark options={solid},forget plot]
  table[row sep=crcr]{%
6	70\\
};
\addplot [color=blue,mark size=6.7pt,only marks,mark=square,mark options={solid},forget plot]
  table[row sep=crcr]{%
7	70\\
};
\addplot [color=blue,mark size=7.4pt,only marks,mark=square,mark options={solid},forget plot]
  table[row sep=crcr]{%
8	70\\
};
\addplot [color=blue,mark size=8.1pt,only marks,mark=square,mark options={solid},forget plot]
  table[row sep=crcr]{%
9	70\\
};
\addplot [color=blue,mark size=8.8pt,only marks,mark=square,mark options={solid},forget plot]
  table[row sep=crcr]{%
10	70\\
};
\addplot [color=mycolor2,only marks,mark=triangle,mark options={solid,rotate=180},forget plot]
  table[row sep=crcr]{%
1	80\\
};
\addplot [color=mycolor2,mark size=2.7pt,only marks,mark=triangle,mark options={solid,rotate=180},forget plot]
  table[row sep=crcr]{%
2	80\\
};
\addplot [color=mycolor2,mark size=3.3pt,only marks,mark=triangle,mark options={solid,rotate=180},forget plot]
  table[row sep=crcr]{%
3	80\\
};
\addplot [color=mycolor2,mark size=4.0pt,only marks,mark=triangle,mark options={solid,rotate=180},forget plot]
  table[row sep=crcr]{%
4	80\\
};
\addplot [color=mycolor2,mark size=4.7pt,only marks,mark=triangle,mark options={solid,rotate=180},forget plot]
  table[row sep=crcr]{%
5	80\\
};
\addplot [color=mycolor2,mark size=5.7pt,only marks,mark=triangle,mark options={solid,rotate=180},forget plot]
  table[row sep=crcr]{%
6	80\\
};
\addplot [color=mycolor2,mark size=6.3pt,only marks,mark=triangle,mark options={solid,rotate=180},forget plot]
  table[row sep=crcr]{%
7	80\\
};
\addplot [color=mycolor2,mark size=7.0pt,only marks,mark=triangle,mark options={solid,rotate=180},forget plot]
  table[row sep=crcr]{%
8	80\\
};
\addplot [color=mycolor2,mark size=7.7pt,only marks,mark=triangle,mark options={solid,rotate=180},forget plot]
  table[row sep=crcr]{%
9	80\\
};
\addplot [color=mycolor2,mark size=8.3pt,only marks,mark=triangle,mark options={solid,rotate=180},forget plot]
  table[row sep=crcr]{%
10	80\\
};
\addplot [color=black,only marks,mark=triangle,mark options={solid},forget plot]
  table[row sep=crcr]{%
1	90\\
};
\addplot [color=black,mark size=2.7pt,only marks,mark=triangle,mark options={solid},forget plot]
  table[row sep=crcr]{%
2	90\\
};
\addplot [color=black,mark size=3.3pt,only marks,mark=triangle,mark options={solid},forget plot]
  table[row sep=crcr]{%
3	90\\
};
\addplot [color=black,mark size=4.0pt,only marks,mark=triangle,mark options={solid},forget plot]
  table[row sep=crcr]{%
4	90\\
};
\addplot [color=black,mark size=4.7pt,only marks,mark=triangle,mark options={solid},forget plot]
  table[row sep=crcr]{%
5	90\\
};
\addplot [color=black,mark size=5.7pt,only marks,mark=triangle,mark options={solid},forget plot]
  table[row sep=crcr]{%
6	90\\
};
\addplot [color=black,mark size=6.3pt,only marks,mark=triangle,mark options={solid},forget plot]
  table[row sep=crcr]{%
7	90\\
};
\addplot [color=black,mark size=7.0pt,only marks,mark=triangle,mark options={solid},forget plot]
  table[row sep=crcr]{%
8	90\\
};
\addplot [color=black,mark size=7.7pt,only marks,mark=triangle,mark options={solid},forget plot]
  table[row sep=crcr]{%
9	90\\
};
\addplot [color=black,mark size=8.3pt,only marks,mark=triangle,mark options={solid},forget plot]
  table[row sep=crcr]{%
10	90\\
};
\addplot [color=red,only marks,mark=triangle,mark options={solid,rotate=90},forget plot]
  table[row sep=crcr]{%
1	100\\
};
\addplot [color=red,mark size=2.7pt,only marks,mark=triangle,mark options={solid,rotate=90},forget plot]
  table[row sep=crcr]{%
2	100\\
};
\addplot [color=red,mark size=3.3pt,only marks,mark=triangle,mark options={solid,rotate=90},forget plot]
  table[row sep=crcr]{%
3	100\\
};
\addplot [color=red,mark size=4.0pt,only marks,mark=triangle,mark options={solid,rotate=90},forget plot]
  table[row sep=crcr]{%
4	100\\
};
\addplot [color=red,mark size=4.7pt,only marks,mark=triangle,mark options={solid,rotate=90},forget plot]
  table[row sep=crcr]{%
5	100\\
};
\addplot [color=red,mark size=5.7pt,only marks,mark=triangle,mark options={solid,rotate=90},forget plot]
  table[row sep=crcr]{%
6	100\\
};
\addplot [color=red,mark size=6.3pt,only marks,mark=triangle,mark options={solid,rotate=90},forget plot]
  table[row sep=crcr]{%
7	100\\
};
\addplot [color=red,mark size=7.0pt,only marks,mark=triangle,mark options={solid,rotate=90},forget plot]
  table[row sep=crcr]{%
8	100\\
};
\addplot [color=red,mark size=7.7pt,only marks,mark=triangle,mark options={solid,rotate=90},forget plot]
  table[row sep=crcr]{%
9	100\\
};
\addplot [color=red,mark size=8.3pt,only marks,mark=triangle,mark options={solid,rotate=90},forget plot]
  table[row sep=crcr]{%
10	100\\
};
\addplot [color=green,only marks,mark=triangle,mark options={solid,rotate=270},forget plot]
  table[row sep=crcr]{%
1	110\\
};
\addplot [color=green,mark size=2.7pt,only marks,mark=triangle,mark options={solid,rotate=270},forget plot]
  table[row sep=crcr]{%
2	110\\
};
\addplot [color=green,mark size=3.3pt,only marks,mark=triangle,mark options={solid,rotate=270},forget plot]
  table[row sep=crcr]{%
3	110\\
};
\addplot [color=green,mark size=4.0pt,only marks,mark=triangle,mark options={solid,rotate=270},forget plot]
  table[row sep=crcr]{%
4	110\\
};
\addplot [color=green,mark size=4.7pt,only marks,mark=triangle,mark options={solid,rotate=270},forget plot]
  table[row sep=crcr]{%
5	110\\
};
\addplot [color=green,mark size=5.7pt,only marks,mark=triangle,mark options={solid,rotate=270},forget plot]
  table[row sep=crcr]{%
6	110\\
};
\addplot [color=green,mark size=6.3pt,only marks,mark=triangle,mark options={solid,rotate=270},forget plot]
  table[row sep=crcr]{%
7	110\\
};
\addplot [color=green,mark size=7.0pt,only marks,mark=triangle,mark options={solid,rotate=270},forget plot]
  table[row sep=crcr]{%
8	110\\
};
\addplot [color=green,mark size=7.7pt,only marks,mark=triangle,mark options={solid,rotate=270},forget plot]
  table[row sep=crcr]{%
9	110\\
};
\addplot [color=green,mark size=8.3pt,only marks,mark=triangle,mark options={solid,rotate=270},forget plot]
  table[row sep=crcr]{%
10	110\\
};
\addplot [color=mycolor1,only marks,mark=star,mark options={solid},forget plot]
  table[row sep=crcr]{%
1	120\\
};
\addplot [color=mycolor1,mark size=4.0pt,only marks,mark=star,mark options={solid},forget plot]
  table[row sep=crcr]{%
2	120\\
};
\addplot [color=mycolor1,mark size=5.0pt,only marks,mark=star,mark options={solid},forget plot]
  table[row sep=crcr]{%
3	120\\
};
\addplot [color=mycolor1,mark size=6.0pt,only marks,mark=star,mark options={solid},forget plot]
  table[row sep=crcr]{%
4	120\\
};
\addplot [color=mycolor1,mark size=7.0pt,only marks,mark=star,mark options={solid},forget plot]
  table[row sep=crcr]{%
5	120\\
};
\addplot [color=mycolor1,mark size=8.5pt,only marks,mark=star,mark options={solid},forget plot]
  table[row sep=crcr]{%
6	120\\
};
\addplot [color=mycolor1,mark size=9.5pt,only marks,mark=star,mark options={solid},forget plot]
  table[row sep=crcr]{%
7	120\\
};
\addplot [color=mycolor1,mark size=10.5pt,only marks,mark=star,mark options={solid},forget plot]
  table[row sep=crcr]{%
8	120\\
};
\addplot [color=mycolor1,mark size=11.5pt,only marks,mark=star,mark options={solid},forget plot]
  table[row sep=crcr]{%
9	120\\
};
\addplot [color=mycolor1,mark size=12.5pt,only marks,mark=star,mark options={solid},forget plot]
  table[row sep=crcr]{%
10	120\\
};
\addplot [color=blue,only marks,mark=star,mark options={solid},forget plot]
  table[row sep=crcr]{%
1	130\\
};
\addplot [color=blue,mark size=4.0pt,only marks,mark=star,mark options={solid},forget plot]
  table[row sep=crcr]{%
2	130\\
};
\addplot [color=blue,mark size=5.0pt,only marks,mark=star,mark options={solid},forget plot]
  table[row sep=crcr]{%
3	130\\
};
\addplot [color=blue,mark size=6.0pt,only marks,mark=star,mark options={solid},forget plot]
  table[row sep=crcr]{%
4	130\\
};
\addplot [color=blue,mark size=7.0pt,only marks,mark=star,mark options={solid},forget plot]
  table[row sep=crcr]{%
5	130\\
};
\addplot [color=blue,mark size=8.5pt,only marks,mark=star,mark options={solid},forget plot]
  table[row sep=crcr]{%
6	130\\
};
\addplot [color=blue,mark size=9.5pt,only marks,mark=star,mark options={solid},forget plot]
  table[row sep=crcr]{%
7	130\\
};
\addplot [color=blue,mark size=10.5pt,only marks,mark=star,mark options={solid},forget plot]
  table[row sep=crcr]{%
8	130\\
};
\addplot [color=blue,mark size=11.5pt,only marks,mark=star,mark options={solid},forget plot]
  table[row sep=crcr]{%
9	130\\
};
\addplot [color=blue,mark size=12.5pt,only marks,mark=star,mark options={solid},forget plot]
  table[row sep=crcr]{%
10	130\\
};
\end{axis}
\end{tikzpicture}%
\end{document}
```

conclusion: `This is LuaTeX, Version beta-0.79.1 (TeX Live 2014) (rev 4971)` has an issue with `pgfplots 1.12`. Is this known to you, @cfeuersaenger? I updated my mac with `tex live utility` to obtain `pgfplots 1.12`and updated all other packages as well.

**Comment by egeerardyn** [comment]
@PeterPablo I can confirm the same behavior here (OS X 10.10, MacTex 2014) from the following LaTeX compilers:

* `pdfTeX 3.14159265-2.6-1.40.15 (TeX Live 2014)` works fine
* `XeTeX 3.14159265-2.6-0.99991 (TeX Live 2014)` works fine
* `LuaTeX, Version beta-0.79.1 (TeX Live 2014) (rev 4971)` produces bad output (as above)

As a work-around for us, probably we could migrate to `xelatex` instead of `lualatex`.

**Comment by PeterPablo** [comment]
xelatex struggles on ACID(47) due to the memory limit and does not know the command `\pdfminorversion` (minor issue). The output of lualtex is plain wrong though.

Here is the pdf for `This is XeTeX, Version 3.14159265-2.6-0.99991 (TeX Live 2014) (preloaded format=xelatex)`: https://www.wuala.com/PeterPablo/Upload/m2t/acid_0e15888_xelatex.pdf/?key=zNl74H2fU0k3
Output looks fine on first sight apart from ACID(47). Let's change I'd say ;-)

**Comment by egeerardyn** [comment]
@PeterPablo : feel free to merge if you feel this is ready (I am quite hesitant to merge my own PRs as I want everything checked by at least two people). The LaTeX compiler is unrelated to those row separators, so it would be better addressed elsewhere.

**Comment by PeterPablo** [comment]
I counted you (+1) and me (+1) = two :-)
