### PR TITLE
Fix has legend

### LINKED ISSUE #607: Octave legend incorrectly detects all entries
```
h = plot(magic(3));
legend(h(2), 'straight line')
```
capture

### PR DESCRIPTION
**Pull request by PeterPablo**
Fixes #607 (Octave legend incorrectly detects all entries)
Supersedes #619 

I furthermore merged tip of `develop`, recreated the hashes and checked the graphical output of changed tests. This only affects octave. Thus matlab output is unchanged and does not have to be checked.

@okomarov, please comment on my fix. I din't understand your last comment in #619.

### CODE REVIEW

**Comment by PeterPablo** [comment]
Travis agrees. Ready for review.

**Comment by okomarov** [comment]
I reckon this type of change needs a visual inspection, but it's just a suggestion. :)

Sent from my iPhone

On 11 May 2015, at 14:45, "Peter Pablo" <notifications@github.com<mailto:notifications@github.com>> wrote:


Travis agrees. Ready for review.

**Comment by PeterPablo** [comment]
> and checked the graphical output of changed tests.
I did visually verify the output of the changed tests.

**Comment by PeterPablo** [comment]
Note: Calling  `ACID(74)`, `ACID(81)`, `ACID(83)` also fails on `develop` (37d139129f59ba73273ad3826b0a7e59856326db).

**Comment by PeterPablo** [comment]
Ok, should be good now.
* Missing hashes re-added
* `ACID(74)` is addressed in #655 
* `ACID(83)` is addressed in #656

**Comment by okomarov** [comment]
:+1:

**Comment by PeterPablo** [comment]
Merged `upstream/develop` and updated hash of `herrorbarPlot` (local octave, mac).

File: src/matlab2tikz.m [hunk 1]
```diff
@@ -950,7 +956,7 @@ function addCustomCode(fid, before, code, after)
             % Make sure that m2t.legendHandles is a row vector.
             for lhandle = m2t.legendHandles(:)'
                 ud = get(lhandle, 'UserData');
-                if isVisible(lhandle) && any(handle == ud.handle)
+                if isAxisVisible(lhandle) && any(handle == ud.handle)
```
Comment (egeerardyn) [inline src/matlab2tikz.m]: Probably we should rename `isAxisVisible` to `isVisibleContainer` to convey the meaning better.

File: test/suites/ACID.m [hunk 2]
```diff
@@ -556,15 +556,14 @@
...
   x = -pi:pi/20:pi;
-  plot( x, cos(x),'-ro',...
-        x, sin(x),'-.b' ...
-      );
-  h = legend( 'cos_x', 'one pretty long legend sin_x', 2 );
-  set( h, 'Interpreter', 'none' );
-  legend boxoff;
+  l = plot(x, cos(x),'-ro',...
+           x, sin(x),'-.b');
+  h = legend(l(2), 'one pretty long legend sin_x (dash-dot)', 'Location', 'northeast');
```
Comment (egeerardyn) [inline test/suites/ACID.m]: This also changes the behavior in MATLAB. I will update the hashes accordingly.

Comment (PeterPablo) [inline test/suites/ACID.m]: True. This should fix/unify #628. The `, 2` seemed to be treated differently.

Comment (PeterPablo) [inline test/suites/ACID.m]: I took the freedom to update the MATLAB hashes myself from my Mac laptop. Hopefully the HG1 hash is fine, since it was created with R2011b.

**Comment by PeterPablo** [comment]
Ready for review.
