### PR TITLE
Axis location 

### LINKED ISSUE #1010: Axis location 'origin' produces /pgfplot/ key mismatch
If I set the XAxisLocation or YAxisLocation property to "origin", latex produces the error:

`Package pgfkeys Error: Choice 'origin' unknown in choice key '/pgfplots/axis y line*'. I am going to ignore this key.`

The correct pgfkeys choice for Matlabs "origin" would be pgfplots "middle".

### PR DESCRIPTION
**Pull request by tgroche**
Fixes #1010

### CODE REVIEW

File: src/matlab2tikz.m [hunk 1]
```diff
@@ -1403,9 +1403,16 @@ case guitypes()
...
+    isXaxisBottom = strcmpi(xLoc, 'bottom');
+    isYaxisLeft   = strcmpi(yLoc, 'left');
 
+    if strcmpi(xLoc, 'origin')
+        xLoc = 'middle';
+    end
+    if strcmpi(yLoc, 'origin')
+        yLoc = 'middle';
+    end
+
```
Comment (miscco) [inline src/matlab2tikz.m]: Seems nice +1
