### PR TITLE
TickLabels - fix escaping

### LINKED ISSUE #710: Percent symbol is not escaped in TickLabel
# Minimal MATLAB working example:
```matlab
plot(1:10)
set(gca,'XTick',5)
set(gca,'XTickLabel','50%')
matlab2tikz('bug.tex')
```

# matlab2tikz .tex output
```tex
...
xtick={5},
xticklabels={{50%}},
...
```

# Expected .tex output
```tex
...
xtick={5},
xticklabels={{50\%}},
...
```

The percent symbol should be escaped.

*(Using commit 33667a0829a3223c8944cc502505b78e3496c8d7)*

### PR DESCRIPTION
**Pull request by PeterPablo**
fixes #710

Note: TickLabels don't currently support different interpreters in MATLAB.

### CODE REVIEW

**Comment by PeterPablo** [comment]
##HG1
|            | Pass | Fail | Skip | Total |
| :--------- | ---: | ---: | ---: | ----: |
| Unreliable |    1 |   21 |    0 |    22 |
|   Reliable |   76 |    0 |    1 |    77 |
|      Total |   77 |   21 |    1 |    99 |

Build passes. :white_check_mark:

##HG2
|            | Pass | Fail | Skip | Total |
| :--------- | ---: | ---: | ---: | ----: |
| Unreliable |    2 |   13 |    0 |    15 |
|   Reliable |   83 |    0 |    1 |    84 |
|      Total |   85 |   13 |    1 |    99 |

Build passes. :white_check_mark:

File: src/matlab2tikz.m [hunk 1]
```diff
@@ -1278,11 +1278,14 @@ function addCustomCode(fid, before, code, after)
 
     keywordTickLabelMode = [upper(axis), 'TickLabelMode'];
     tickLabelMode = get(handle, keywordTickLabelMode);
-    keywordTickLabel = [upper(axis), 'TickLabel'];
-    tickLabels = cellstr(get(handle, keywordTickLabel));
     if strcmpi(tickLabelMode, 'auto') && ~m2t.cmdOpts.Results.strict
         pgfTickLabels = [];
     else % strcmpi(tickLabelMode,'manual') || m2t.cmdOpts.Results.strict
+        keywordTickLabel = [upper(axis), 'TickLabel'];
+        interpreter = 'none'; % MATLAB only supports 'none'
```
Comment (egeerardyn) [inline src/matlab2tikz.m]: In HG1, that seems to be the case.
However, in HG2 the [interpreter for axes](http://www.mathworks.com/matlabcentral/answers/102053#comment_300079) can be set (and the default is seems to be the `tex` interpreter).

I think we can just replace the line
`interpreter = 'none';` 
with
```matlab
interpreter = getOrDefault(handle, 'TickLabelInterpreter', 'none');
% HG2 allows to set this property, HG1 tacitly uses the interpreter 'none'
% See http://www.mathworks.com/matlabcentral/answers/102053#comment_300079
```

**Comment by egeerardyn** [comment]
Code seems fine to me. :+1: I think we can quickly add support for HG2 as well (I don't mind adding it myself upon merging, if you want to have a go at more creative things: just let me know).

**Comment by PeterPablo** [comment]
Thanks for digging deeper. I looked it up, but didn't notice that this changed with HG2.
Test with:
```matlab
plot(1:10)
set(gca,'XTick',[3,5])
set(gca,'XTickLabel',{'50\%', '$70^2 \pi$'})
set(gca,'TickLabelInterpreter','latex')
```

**Comment by egeerardyn** [comment]
On HG2 (R2014b/Mac), I get the following plot:
screen shot 2015-08-04 at 15 47 10

Also, when I don't do anything and assign, e.g. `set(gca,'XTickLabel', '50_i')`, the `i` gets subscripted as is expected behavior for the `tex` interpreter).
