### PR TITLE
fix ACID(69) for octave

### LINKED ISSUE #515: ACID test 68 latexInterpreter and 69 latexmath2 fail
These tests fail in octave 3.8.2 because some double `$$` are present in the tex output.

### PR DESCRIPTION
**Pull request by PeterPablo**
* octave does not know the property 'pos'
* introduced by commit 41b415bab9da520e9c850f1b387987f36fc40a35

requires PR #520
fixes #515

### CODE REVIEW

**Comment by PeterPablo** [comment]
R2014b
image

octave 3.8.2
image

File: src/matlab2tikz.m [hunk 1]
```diff
@@ -2665,7 +2665,7 @@ case size(cData,2) % specific y-data is given
                 %       http://www.mathworks.com/support/bugreports/368385
                 oldPos = get(h, 'Position');
                 set(h,'Units','centimeters')
-                pos    = get(h,'pos');
+                pos    = get(h, 'Position');
                 pos    = pos(1:npos);
```
Comment (okomarov) [inline src/matlab2tikz.m]: Bad habit of mine. Now, I have an incentinve to lose it :smile:
